[CRB-202] Add RegisterDealOrder command
gluwa/Creditcoin-Processor-Rust pull request #15
Opened 2021-10-07 18:50 UTC by nathanwhit

This PR implements the RegisterDealOrder command, which creates an simpler entry point for recording loans.

This is based on the changes from #8 and #12, so this is blocked on both of those PRs being merged.

2021-10-11 20:24 UTC, atodorov requested changes
@nathanwhit one of the negative test cases I'm working on fails with a slightly mismatching error message
```
  X InvalidExpiration_Neg [47ms]
  Error Message:
     Expected string length 60 but was 53. Strings differ at index 53.
  Expected: "Transaction status: INVALID;  Message: Invalid number format"
  But was:  "Transaction status: INVALID;  Message: Invalid number"
```

All of the others use "Invalid number format". I didn't see this in the diff but maybe you know where it is coming from. I advocate for consistency. More tests to come soon. See https://github.com/gluwa/Creditcoin-Tests/pull/25

2021-10-11 21:06 UTC, nathanwhit commented
> 
> 
> @nathanwhit one of the negative test cases I'm working on fails with a slightly mismatching error message
> 
> ```
>   X InvalidExpiration_Neg [47ms]
>   Error Message:
>      Expected string length 60 but was 53. Strings differ at index 53.
>   Expected: "Transaction status: INVALID;  Message: Invalid number format"
>   But was:  "Transaction status: INVALID;  Message: Invalid number"
> ```
> 
> All of the others use "Invalid number format". I didn't see this in the diff but maybe you know where it is coming from. I advocate for consistency. More tests to come soon. See [gluwa/Creditcoin-Tests#25](https://github.com/gluwa/Creditcoin-Tests/pull/25)

So the `Invalid number` message is a quirk from the C++ transaction processor. It also appears in the [addOffer tests](https://github.com/gluwa/Creditcoin-Tests/blob/c57fd7265fa0117fe7e6e6bfd86067126facff0f/Creditcoin.NUnitTests/AddOfferTests.cs#L126-L134). I agree with making the message consistent, I'll go ahead and make that change.

2021-10-13 13:34 UTC, atodorov commented on src/handler.rs
> +                "The transaction has already been registered",
@nathanwhit according to the ticket description the message should be "The transfer has already been registered". Let me know if you'd like to adjust it or if I should do it on my end. 

```
  Failed TransferAlreadyRegistered_Neg [5 m 34 s]
  Error Message:
     Expected string length 79 but was 82. Strings differ at index 48.
  Expected: "...NVALID;  Message: The transfer has already been registered"
  But was:  "...NVALID;  Message: The transaction has already been registered"
  -----------------------------------------^
```

2021-10-13 19:17 UTC, atodorov requested changes

2021-10-13 19:17 UTC, atodorov commented on src/handler.rs
> +            dst_address: bid_address.value,
@nathanwhit I think these should be `ask_address_id` and `bid_address_id`, see the details at
https://github.com/gluwa/Creditcoin-Tests/pull/25#discussion_r728375218

2021-10-15 17:33 UTC, nathanwhit commented on src/handler.rs
> +            dst_address: bid_address.value,
Yup you're right, fixed now.

2021-10-15 17:34 UTC, nathanwhit commented on src/handler.rs
> +                "The transaction has already been registered",
Fixed in latest commit, thanks for pointing it out.

2021-10-15 18:37 UTC, atodorov approved these changes
After the latest changes all tests from https://github.com/gluwa/Creditcoin-Tests/pull/25 report PASS.

2021-11-11 17:47 UTC, atodorov commented
@nathanwhit , @CAGS295 ping. Can we merge this PR? I don't see a reason for it staying open. Previous comment indicates tests have passed (I had tested against a custom built docker image).

2021-11-16 18:14 UTC, atodorov commented
@nathanwhit #8 and #20 (replacement for #20) have been now merged. Can you please rebase this PR so I can rebuild the docker image & retest it.

2021-11-16 18:26 UTC, nathanwhit commented
@atodorov Rebased

2021-11-17 16:02 UTC, seandeneen-gluwa approved these changes

2021-11-17 19:25 UTC, CAGS295 approved these changes

2021-11-18 20:11 UTC, atodorov commented
After additional investigation of change deltas we agree that this looks good. Merging.

2021-11-18 20:11 UTC, merged