Fixing various issues with block verification
gluwa/Creditcoin-Processor-Rust pull request #19
Opened 2021-11-03 02:10 UTC by vladimir-gluwa

To fix block verification in sawtooth 1.2 - the following PRs are all related and should be reviewed together:
CRB-236/sdk-accepts-block-num-for-list-by-prefix
CRB-236/validator-fixes-block-verification
CRB-236/tp-fixes-block-verification
CRB-236/core-updating-tx-version

2021-11-15 20:39 UTC, nathanwhit requested changes
One comment. After that is resolved and once the SDK changes are merged, providing CI is passing, this looks fine to me.

2021-11-16 19:04 UTC, nathanwhit commented on src/handler.rs
> +            _ => Integer::from(278910),
What is the significance of `277800` and `278910`? A named constant or a comment here would make this easier to understand.

2021-11-19 20:11 UTC, atodorov requested changes
@vladimir-gluwa this PR needs rebase + resolving a few conflicts.

2021-11-24 19:47 UTC, vladimir-gluwa commented on src/handler.rs
> +            _ => Integer::from(278910),
there is a comment that says "for historical reasons update block is calculated as the following", the numbers are unique and "random" in a sence that they have occured naturally when we changed the formula; i don't really see how calling them, say UPDATE_BLOCK_NEW_FORMULA and  UPDATE_BLOCK_OLD_FORMULA makes it much more readable

2021-11-24 20:31 UTC, nathanwhit commented on src/handler.rs
> +            _ => Integer::from(278910),
I see, but for future readers of this code these numbers appear to be pulled from thin air. It would be nice to have it documented where these values were derived from (I assume from the production chain).

Assuming these values are derived from the production blockchain, then why does it make sense to always apply this logic? These block numbers have no meaning with respect to an arbitrary creditcoin chain (for instance the testnet), where we wouldn't need this legacy logic for backwards compatibility.

2021-11-26 01:01 UTC, vladimir-gluwa commented on src/handler.rs
> +            _ => Integer::from(278910),
i updated the comment and code; as to always applying the logic - as far as we concerned there is only one creditcoin (production blockchain) just as there is only one bitcoin or bitcoin cash blockchain, so whether any other, not ours, blockchain has the same or different behavior doesn't matter; as to our testnet - behaving the same way as production is a good thing, no?

2021-11-26 12:57 UTC, atodorov commented
Note: this PR hasn't been rebased, instead there has been some merging of branches which is a bit different. 
I've done my best to rebase & clean up the conflicts in https://github.com/gluwa/Creditcoin-Processor-Rust/pull/23. 

@vladimir-gluwa let me know if I am missing something. I can also force push into this branch/PR if you want.

2021-12-01 17:41 UTC, nathanwhit commented
Replaced by #23

2021-12-01 17:41 UTC, closed without merging