[CRB-285] Pass head ID to filter operations to avoid block lookup errors
gluwa/Creditcoin-Processor-Rust pull request #38
Opened 2021-12-13 19:08 UTC by nathanwhit

## Description Of Changes
This PR pairs with [this Sawtooth Core PR](https://github.com/gluwa/Sawtooth-Core/pull/50) to make the transaction processor more resilient to forks and more deterministic. Currently we fall back to requesting blocks by block number in some cases. This is non-deterministic and can cause blocks to incorrectly be marked invalid if the desired block is not yet committed to the block store. By passing a head ID, we can look up the appropriate block through the block manager in Sawtooth, which contains all blocks which are not committed and therefore requests that go through the block manager should not fail.

## Code Review Checklist

- [x] Target branch is `dev`, unless we're merging from `dev` to `main`
- [ ] All CI checks reports PASS

2021-12-13 21:46 UTC, atodorov commented
@nathanwhit code changes look good but what would be the scenario for testing this change? We've got nodes that have forked, what is the expected behavior that we should see ?

2021-12-15 18:04 UTC, nathanwhit commented
@atodorov So the changes here are exercised only if we are running housekeeping with a non-zero block number (which we haven't done in a while). Validating old blocks with non-zero housekeeping is how I encountered the bug. The changes on the sawtooth-core side should be exercised just through normal operation, particularly when we issue block rewards.

2021-12-15 19:40 UTC, atodorov requested changes
The changed lines in this PR however trivial aren't covered by any unit tests. Need to add some.

2021-12-21 16:45 UTC, seandeneen-gluwa approved these changes

2021-12-21 17:41 UTC, atodorov approved these changes

2021-12-21 18:34 UTC, merged