Fix inverted branch in award function
gluwa/Creditcoin-Processor-Rust pull request #52
Opened 2022-01-06 19:01 UTC by nathanwhit

## Description Of Changes
There is a typo in the award function when using the new formula that inverts a branch. This causes errors in revalidation or syncing with the production chain from scratch.

## Code Review Checklist

- [ ] Target branch is `dev`, unless we're merging from `dev` to `main`
- [ ] All CI checks reports PASS

2022-01-07 18:02 UTC, atodorov requested changes

2022-01-07 18:02 UTC, atodorov commented on src/handler.rs
> +            format!("{}{:0<18}", &fraction_str[..pos], &fraction_str[pos + 1..])
This function doesn't seem to have any tests.

2022-01-07 21:16 UTC, nathanwhit commented on src/handler.rs
> +            format!("{}{:0<18}", &fraction_str[..pos], &fraction_str[pos + 1..])
Added a couple tests to cover each of the branches

2022-01-12 17:00 UTC, nathanwhit commented
Ping @CAGS295, @seandeneen-gluwa this still needs review

2022-01-12 23:48 UTC, seandeneen-gluwa approved these changes

2022-01-13 19:01 UTC, atodorov approved these changes

2022-01-13 19:10 UTC, merged