CRB-307
gluwa/Creditcoin-Processor-Rust pull request #71
Opened 2022-02-01 00:56 UTC by CAGS295

## Description Of Changes
The chain had a block with housekeeping where no miners where rewarded but the last processed block id got incremented.
The reproducible case is still unknown. Bail the transaction if there are no signatures to reward.

## Code Review Checklist

- [X] Target branch is `dev`, unless we're merging from `dev` to `main`
- [ ] All CI checks reports PASS

2022-02-08 01:53 UTC, vladimir-gluwa approved these changes

2022-02-09 18:50 UTC, atodorov requested changes
@CAGS295 tests.rs, line 3680 is causing failure with the latest changes. I'm not sure how do we want to change this in order to have the test passing again.

2022-03-10 19:06 UTC, atodorov approved these changes

2022-03-10 19:23 UTC, atodorov requested changes
https://github.com/gluwa/Creditcoin-Processor-Rust/pull/71#pullrequestreview-877915402

2022-03-10 20:36 UTC, atodorov approved these changes

2022-03-10 20:36 UTC, merged